= An InfoQ Mini-Book

This book is written in http://asciidoctor.org/[Asciidoctor]. It compiles to HTML, PDF, EPUB, and MOBI using the Asciidoctor Gradle plugin.

== Building

To convert this book to HTML, PDF, EPUB, and MOBI, install https://www.amazon.com/gp/feature.html?docId=1000765211[KindleGen], change `build.sh` to point to your installation, then run the following command:

[source]
----
$ build.sh
----

* Open _build/asciidoc/html5/index.html_ in your browser to see the generated HTML file.
* Open _build/asciidoc/pdf/index.pdf_ in a PDF Reader to see the generated PDF file.
* Open _build/asciidoc/epub3/index.epub_ in iBooks to see the generated EPUB file.
* Open _build/asciidoc/epub3/index.mobi_ in http://calibre-ebook.com/[Calibre] to see the generated MOBI file.

== Sweet Authoring Experience
If you'd like a very pleasant authoring experience, the project provides build files that make it possible. First of all,
you'll need to run `gradlew` once. After running it once, you can run `./gradlew watch` to watch for any changes and
recompile files as you save them.

To have a similar awesome experience (watch and auto-reload) in your browser, install https://nodejs.org/[Node.js] on your machine.

After installing Node, you can run the following command to install development tools (like http://www.browsersync.io/[Browsersync]).
You will only need to run this command when dependencies change in `package.json`.

[source]
----
npm install
----

Now you can run the `grunt` command to create a blissful development experience where your browser auto-refreshes
when files change on your hard drive.
