= My Book

This is an awesome book. It's written in AsciiDoc and compiles to HTML, PDF, EPUB using the
http://asciidoctor.org/docs/asciidoctor-gradle-plugin/[Asciidoctor Gradle plugin].

== Installing

----
npm run setup
----

If that fails with an error like ./gradlew: Syntax error: word unexpected (expecting "in"), then run the following command to fix the gradlew file:

----
sed -i.bak 's/\r$//' gradlew
----

== Building

To convert this book to HTML, EPUB, run the following command:

----
$ npm run build
----

To convert this book to a 6x9" PDF for printing:

----
$ generate-pdf.sh
----

To convert this book to a 8.5x11" PDF for downloading:

----
$ generate-pdf.sh screen
----

* Open _build/asciidoc/html5/index.html_ in your browser to see the generated HTML file.
* Open _build/asciidoc/pdf-prepress/index.pdf_ to see the 6x9" printable PDF file.
* Open _build/asciidoc/pdf-screen/index.pdf_ to see the downloadable 8.5x11" PDF file.
* Open _build/asciidoc/epub3/index.epub_ in iBooks to see the generated EPUB file.

[NOTE]
====
To be able to generate the PDF, you need have some dependencies installed.

First, install https://rvm.io/rvm/install#basic-install[RVM] to manage your Ruby installation(s).
Once RVM is installed and loaded, run the following commands:

. `rvm install 2.6`
. `rvm use 2.6`
. `gem install bundler`

The `generate-pdf.sh` script will then use Bundler to install the dependencies it needs.
====

== Sweet Authoring Experience

If you'd like a very pleasant authoring experience, the project provides build files that make it possible. First of all,
you'll need to run `gradlew` once. After running it once, you can run `./gradlew watch` to watch for any changes and
recompile files as you save them.

To have a similar awesome experience (watch and auto-reload) in your browser, install https://nodejs.org/[Node.js] on your machine.

After installing Node, you can run the following command to install development tools (like http://www.browsersync.io/[Browsersync]).
You will only need to run this command when dependencies change in `package.json`.

----
npm install
----

Now you can run the following command:

----
npm run watch
----

This will start two daemons:

. Gradle, which will watch the file system and rebuild the HTML version continuously using AsciiDoctor
. BrowserSync, which will serve the updated HTML version all of the time and make it available over HTTP

Thanks to this, you'll have a constantly up to date HTML version available in your browser while editing.
