name: Book CI
on:
  push:
    branches: # build any changes to main
      - main
    tags: # all tags
      - '*'
  pull_request: # build all PRs
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build book
      run: npm run setup
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Build print PDF
      run: ./generate-pdf.sh
    - name: Build downloadable PDF
      run: ./generate-pdf.sh screen
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: book-${{ matrix.os }}
        path: build/asciidoc
