name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build book
        run: npm run setup
      - name: Rename files
        run: |
          find ./build -type f -name "index.*" | while read fname; do
            dirname=`dirname "$fname"`
            foldername=`basename "$dirname"`
            filename=`basename "$fname"`
            extension="${filename##*.}"
            cp "${dirname}/${filename}" "./build/${{ github.event.repository.name }}-${foldername}-${{ github.event.release.tag_name }}.${extension}"
          done
          cd ./build/asciidoc/html5
          zip -r ${{ github.event.repository.name }}-html5-${{ github.event.release.tag_name }}.zip **
          mv *.zip ../..
      - name: Upload release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/{*.pdf,*.epub,*.zip}"]'
