name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build book
        run: npm run setup
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Rename files
        run: |
          find ./build -type f -name "index.*" | while read fname; do
            dirname=`dirname "$fname"`
            foldername=`basename "$dirname"`
            filename=`basename "$fname"`
            extension="${filename##*.}"
            cp "${dirname}/${filename}" "./build/${{ github.event.repository.name }}-${foldername}-${{ env.RELEASE_VERSION }}.${extension}"
          done
          cd ./build/asciidoc/html5
          zip -r ${{ github.event.repository.name }}-html5-${{ env.RELEASE_VERSION }}.zip **
          mv *.zip ../..
      - name: Upload release
        uses: alexellis/upload-assets@0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["build/{*.pdf,*.epub,*.zip}"]'
